apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: library
type: Opaque
stringData:
  database-url: postgresql://library_user:library_pass@postgres-service:5432/library_db
  jwt-secret-key: super-secret-key-change-in-production
